### PR TITLE
Use (anonymous) mmap() when available.

### LINKED ISSUE #147: BlockImpTest failures with Clang 8 on RHEL8
On latest master:

`98% tests passed, 4 tests failed out of 178

Total Test time (real) =  29.15 sec

The following tests FAILED:
	 25 - BlockImpTest (SEGFAULT)
	 26 - BlockImpTest_optimised (SEGFAULT)
	 27 - BlockImpTest_legacy (SEGFAULT)
	 28 - BlockImpTest_legacy_optimised (SEGFAULT)`

`$ lldb Test/BlockImpTest
(lldb) target create "Test/BlockImpTest"
Current executable set to 'Test/BlockImpTest' (x86_64).
(lldb) run
Process 4784 launched: '/home/ares/labs2/libobjc2/Build/Test/BlockImpTest' (x86_64)
Process 4784 stopped
* thread #1, name = 'BlockImpTest', stop reason = signal SIGSEGV: address access protected (fault address: 0x652000)
    frame #0: 0x0000000000652000
->  0x652000: movq   -0x1007(%rip), %rsi
    0x652007: xchgq  %rsi, %rdi
    0x65200a: jmpq   *-0x1008(%rip)
    0x652010: movq   -0x1007(%rip), %rsi
(lldb) bt
* thread #1, name = 'BlockImpTest', stop reason = signal SIGSEGV: address access protected (fault address: 0x652000)
  * frame #0: 0x0000000000652000
    frame #1: 0x00000000004016fa BlockImpTest`main at BlockImpTest.m:38:2
    frame #2: 0x00007ffff75d9873 libc.so.6`.annobin_libc_start.c + 243
    frame #3: 0x000000000040140e BlockImpTest`.annobin_init.c.hot + 46`

### PR DESCRIPTION
**Pull request by ngrewe**
Should fix #147 (SELinux related segfault)

### CODE REVIEW

File: block_to_imp.c [hunk 1]
```diff
@@ -162,6 +167,8 @@ static struct trampoline_set *alloc_trampolines(char *start, char *end)
 	struct trampoline_set *metadata = calloc(1, sizeof(struct trampoline_set));
 #if _WIN32
 	metadata->buffers = VirtualAlloc(NULL, sizeof(struct trampoline_buffers), MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
+#elif defined(HAVE_MAP_ANONYMOUS)
```
Comment (davidchisnall) [inline block_to_imp.c]: I don't think that we need this conditional.  `posix_memalign` is likely to be less portable than `mmap`, so there's little value in having it as a fallback.
